apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext657
  labels:
    app: BoundedContext657
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext657
  template:
    metadata:
      labels:
        app: BoundedContext657
    spec:
      containers:
        - name: BoundedContext657
          image: username/BoundedContext657:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
